#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

init2b: init2b.c
	$(CC) $(CFLAGS) -o init2b init2b.c

clean:
	rm -f init2b 
