#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

init2b.exe: init2b.c
	$(CC) $(CFLAGS) -einit2b init2b.c

clean:
	erase init2b.exe
