#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

tri.exe: tri.c
	@echo "This program will fail to compile"
	$(CC) $(CFLAGS) -etri tri.c

clean:
	erase tri.exe
