#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

tri: tri.c
	$(CC) $(CFLAGS) -o tri tri.c

clean:
	rm -f tri 
