#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

tmp-name.exe: tmp-name.c
	$(CC) $(CFLAGS) -etmp-name tmp-name.c

clean:
	erase tmp-name.exe
