#-----------------------------------------------#
#	Makefile for dos systems		#
#    using a Microsoft Visual C++ compiler	#
#-----------------------------------------------#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1

two.exe: two.c
	$(CC) $(CFLAGS) two.c

clean:
	erase two.exe 
