#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

ia: ia.c
	$(CC) $(CFLAGS) -o ia ia.c

clean:
	rm -f ia 
