#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

matrix: matrix.c
	$(CC) $(CFLAGS) -o matrix matrix.c

clean:
	rm -f matrix 
