#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

rev: rev.c
	$(CC) $(CFLAGS) -o rev rev.c

clean:
	rm -f rev 
