#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

flush2.exe: flush2.c
	$(CC) $(CFLAGS) -eflush2 flush2.c

clean:
	erase flush2.exe
