#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

max.exe: max.c
	@echo "This program will fail to compile using $(CC)"
	$(CC) $(CFLAGS) -emax max.c

clean:
	erase max.exe
