#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

twice: twice.c
	$(CC) $(CFLAGS) -o twice twice.c

clean:
	rm -f twice 
