#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

xgets: xgets.c
	$(CC) $(CFLAGS) -o xgets xgets.c

clean:
	rm -f xgets 
