#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

calc1.exe: calc1.c
	$(CC) $(CFLAGS) -ecalc1 calc1.c

clean:
	erase calc1.exe
