#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

calc1: calc1.c
	$(CC) $(CFLAGS) -o calc1 calc1.c

clean:
	rm -f calc1 
