#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

len.exe: len.c
	$(CC) $(CFLAGS) -elen len.c

clean:
	erase len.exe
