#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

calc3.exe: calc3.c
	$(CC) $(CFLAGS) -ecalc3 calc3.c

clean:
	erase calc3.exe
