#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

simple: simple.c
	$(CC) $(CFLAGS) -o simple simple.c

clean:
	rm -f simple 
