#-----------------------------------------------#
#	Makefile for dos systems		#
#    using a Microsoft Visual C++ compiler	#
#-----------------------------------------------#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1

simple.exe: simple.c
	$(CC) $(CFLAGS) simple.c

clean:
	erase simple.exe 
