#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

base2: base2.c
	$(CC) $(CFLAGS) -o base2 base2.c

clean:
	rm -f base2 
