#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

base2.exe: base2.c
	$(CC) $(CFLAGS) -c -ebase2 base2.c

clean:
	erase base2.exe
