#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

not2: not2.c
	$(CC) $(CFLAGS) -o not2 not2.c

clean:
	rm -f not2 
