#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

xgets2: xgets2.c
	$(CC) $(CFLAGS) -o xgets2 xgets2.c

clean:
	rm -f xgets2 
