#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

xgets2.obj: xgets2.c
	$(CC) $(CFLAGS) -c xgets2.c

clean:
	erase xgets2.obj
