#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

full1: full1.c
	$(CC) $(CFLAGS) -o full1 full1.c

clean:
	rm -f full1 
