#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

sum: sum.c
	$(CC) $(CFLAGS) -o sum sum.c

clean:
	rm -f sum 
