#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

sum.exe: sum.c
	@echo "This program fails to compile"
	$(CC) $(CFLAGS) -esum sum.c

clean:
	erase sum.exe
