#-----------------------------------------------#
#	Makefile for dos systems		#
#    using a Microsoft Visual C++ compiler	#
#-----------------------------------------------#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1

sum.exe: sum.c
	@echo "This program will generate errors"
	$(CC) $(CFLAGS) sum.c

clean:
	erase sum.exe 
