#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

init2a.exe: init2a.c
	$(CC) $(CFLAGS) -einit2a init2a.c

clean:
	erase init2a.exe
