#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

flush: flush.c
	$(CC) $(CFLAGS) -o flush flush.c

clean:
	rm -f flush 
