#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

sqr-i.exe: sqr-i.c
	$(CC) $(CFLAGS) -esqr-i sqr-i.c

clean:
	erase sqr-i.exe
