#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

init-a.exe: init-a.c
	@echo "This program will generate a warning"
	$(CC) $(CFLAGS) -einit-a init-a.c

clean:
	erase init-a.exe
