#-----------------------------------------------#
#	Makefile for dos systems		#
#    using a Microsoft Visual C++ compiler	#
#-----------------------------------------------#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1

init-a.exe: init-a.c
	@echo "This program generates warnings"
	$(CC) $(CFLAGS) init-a.c

clean:
	erase init-a.exe 
