#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

init-a: init-a.c
	$(CC) $(CFLAGS) -o init-a init-a.c

clean:
	rm -f init-a 
