#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

loop: loop.c
	$(CC) $(CFLAGS) -o loop loop.c

clean:
	rm -f loop 
