#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

scat.exe: scat.c
	@echo "This program will generate an error"
	$(CC) $(CFLAGS) -escat scat.c

clean:
	erase scat.exe
