#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

scat: scat.c
	$(CC) $(CFLAGS) -o scat scat.c

clean:
	rm -f scat 
