#-----------------------------------------------#
#	Makefile for dos systems		#
#    using a Microsoft Visual C++ compiler	#
#-----------------------------------------------#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1

scat.exe: scat.c
	@echo "This program generates warnings"
	$(CC) $(CFLAGS) scat.c

clean:
	erase scat.exe 
