#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

seven: seven.c
	$(CC) $(CFLAGS) -o seven seven.c

clean:
	rm -f seven 
