#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

total5w: total5w.c
	$(CC) $(CFLAGS) -o total5w total5w.c

clean:
	rm -f total5w 
