#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

total5w.exe: total5w.c
	$(CC) $(CFLAGS) -etotal5w total5w.c

clean:
	erase total5w.exe
