#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

tmp2: tmp2.c
	$(CC) $(CFLAGS) -o tmp2 tmp2.c

clean:
	rm -f tmp2 
