#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

tmp2.exe: tmp2.c
	$(CC) $(CFLAGS) -etmp2 tmp2.c

clean:
	erase tmp2.exe
