#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

ret.exe: ret.c 
	@echo "The compile is smart enough to catch the error in this file"
	$(CC) $(CFLAGS) -eret ret.c 

clean:
	erase ret.exe
