#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

ptr2.exe: ptr2.c
	$(CC) $(CFLAGS) -eptr2 ptr2.c

clean:
	erase ptr2.exe
