#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

totalb: totalb.c
	$(CC) $(CFLAGS) -o totalb totalb.c

clean:
	rm -f totalb 
