#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

full2: full2.c
	$(CC) $(CFLAGS) -o full2 full2.c

clean:
	rm -f full2 
