#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

hello: hello.c
	$(CC) $(CFLAGS) -o hello hello.c

clean:
	rm -f hello 
