#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

q_zero.exe: q_zero.c
	$(CC) $(CFLAGS) -eq_zero q_zero.c

clean:
	erase q_zero.exe
