#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

thing: thing.c
	$(CC) $(CFLAGS) -o thing thing.c

clean:
	rm -f thing 
