#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

tri-sub.obj: tri-sub.c
	$(CC) $(CFLAGS) -c tri-sub.c

clean:
	erase tri-sub.obj
