#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

fib: fib.c
	$(CC) $(CFLAGS) -o fib fib.c

clean:
	rm -f fib 
