#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

param2: param2.c
	$(CC) $(CFLAGS) -o param2 param2.c

clean:
	rm -f param2 
