#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

cstop.exe: cstop.c
	$(CC) $(CFLAGS) -c -ecstop cstop.c

clean:
	erase cstop.exe
