#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

cstop: cstop.c
	$(CC) $(CFLAGS) -o cstop cstop.c

clean:
	rm -f cstop 
