#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

fun-file.exe: fun-file.c
	$(CC) $(CFLAGS) -efun-file fun-file.c

clean:
	erase fun-file.exe
