#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

fun-file: fun-file.c
	$(CC) $(CFLAGS) -o fun-file fun-file.c

clean:
	rm -f fun-file 
