#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

calc2.exe: calc2.c
	$(CC) $(CFLAGS) -ecalc2 calc2.c

clean:
	erase calc2.exe
