#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

calc2: calc2.c
	$(CC) $(CFLAGS) -o calc2 calc2.c

clean:
	rm -f calc2 
