#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

ptr3: ptr3.c
	$(CC) $(CFLAGS) -o ptr3 ptr3.c

clean:
	rm -f ptr3 
