#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

ptr3.exe: ptr3.c
	$(CC) $(CFLAGS) -eptr3 ptr3.c

clean:
	erase ptr3.exe
