#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

copy: copy.c
	$(CC) $(CFLAGS) -o copy copy.c

clean:
	rm -f copy 
