#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

owe0.exe: owe0.c
	$(CC) $(CFLAGS) -eowe0 owe0.c

clean:
	erase owe0.exe
