#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

p_array: p_array.c
	$(CC) $(CFLAGS) -o p_array p_array.c

clean:
	rm -f p_array 
