#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

graph: graph.c
	$(CC) $(CFLAGS) -o graph graph.c

clean:
	rm -f graph 
