#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

wbin.exe: wbin.c
	$(CC) $(CFLAGS) -ewbin wbin.c

clean:
	erase wbin.exe
