#-----------------------------------------------#
#	Makefile for dos systems		#
#    using a Microsoft Visual C++ compiler	#
#-----------------------------------------------#
CC=cl
#
# Flags 
#	AL -- Compile for large model
#	Zi -- Enable debugging
#	W1 -- Turn on warnings
#
CFLAGS=/AL /Zi /W1 /D__MSDOS__

wbin.exe: wbin.c
	$(CC) $(CFLAGS) wbin.c

clean:
	erase wbin.exe 
