#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

PROG: PROG.c
	$(CC) $(CFLAGS) -o PROG PROG.c

clean:
	rm -f PROG 
