#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

sqr.exe: sqr.c
	$(CC) $(CFLAGS) -esqr sqr.c

clean:
	erase sqr.exe
