#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

sqr: sqr.c
	$(CC) $(CFLAGS) -o sqr sqr.c

clean:
	rm -f sqr 
