#
# Makefile for Borland's Borland-C++ compiler
#
CC=bcc
#
# Flags 
#     	-N  -- Check for stack overflow
#	-v  -- Enable debugging
#	-w  -- Turn on all warnings
#	-ml -- Large model
#
CFLAGS=-N -v -w -ml

copy2.exe: copy2.c
	@echo "This program generates warnings"
	$(CC) $(CFLAGS) -ecopy2 copy2.c

clean:
	erase copy2.exe
