#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

vars: vars.c
	$(CC) $(CFLAGS) -o vars vars.c

clean:
	rm -f vars 
