#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

len2: len2.c
	$(CC) $(CFLAGS) -o len2 len2.c

clean:
	rm -f len2 
