#-----------------------------------------------#
#	Makefile for unix systems		#
#    using a GNU C compiler			#
#-----------------------------------------------#
CC=cc
CFLAGS=-g 
#
# Compiler flags:
#	-g	-- Enable debugging

cent: cent.c
	$(CC) $(CFLAGS) -o cent cent.c

clean:
	rm -f cent 
